apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: prod-

labels:
  - pairs:
      environment: prod
    includeSelectors: true

patches:
  - path: deployment-patch.yaml
  - target:
      kind: Service
      name: service-devops
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 54000
      - op: add
        path: /spec/externalIPs
        value: ["10.0.2.15"]
